name: challenge_flutter
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png

  android_12:
    color: "#ffffff"
    image: assets/splash.png
